otel-metrics-pipeline:
  workers: 8
  delay: 3000
  source:
    otel_metrics_source:
      health_check_service: true
      ssl: false
      unframed_requests: true
      port: 4905
  buffer:
    bounded_blocking:
      buffer_size: 1024
      batch_size: 1024
  processor:
    - otel_metrics:
        calculate_histogram_buckets: true
        calculate_exponential_histogram_buckets: true
        exponential_histogram_max_allowed_scale: 10
        flatten_attributes: false
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: custom
        index: deneme-metrics-otel
        template_type: index-template
        template_content: >
          {
            "index_patterns": [
              "deneme-metrics-otel*"
            ],
            "data_stream": {},
            "template": {
              "mappings": {
                "_meta": {
                  "version": "1.0.0",
                  "catalog": "observability",
                  "type": "metrics",
                  "component": "metrics",
                  "correlations" : [
                    {
                      "field": "spanId",
                      "foreign-schema" : "traces",
                      "foreign-field" : "spanId"
                    },
                    {
                      "field": "traceId",
                      "foreign-schema" : "traces",
                      "foreign-field" : "traceId"
                    }
                  ]
                },
                "_source": {
                  "enabled": true
                },
                "dynamic_templates": [
                  {
                    "exemplar_attributes_map": {
                      "mapping": {
                        "type": "keyword"
                      },
                      "path_match": "exemplar.attributes.*"
                    }
                  },
                  {
                    "instrumentation_scope_attributes_map": {
                      "mapping": {
                        "type": "keyword"
                      },
                      "path_match": "instrumentationScope.attributes.*"
                    }
                  }
                ],
                "properties": {
                  "serviceName": {
                    "type": "keyword",
                    "time_series_dimension": true
                  },
                  "name": {
                    "type": "keyword",
                    "ignore_above": 256,
                    "time_series_dimension": true
                  },
                  "attributes": {
                    "type": "object",
                    "properties": {
                      "data_stream": {
                        "properties": {
                          "dataset": {
                            "ignore_above": 128,
                            "type": "keyword"
                          },
                          "namespace": {
                            "ignore_above": 128,
                            "type": "keyword"
                          },
                          "type": {
                            "ignore_above": 56,
                            "type": "keyword"
                          }
                        }
                      }
                    }
                  },
                  "description": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  },
                  "unit": {
                    "type": "keyword",
                    "ignore_above": 128
                  },
                  "kind": {
                    "type": "keyword",
                    "ignore_above": 128
                  },
                  "aggregationTemporality": {
                    "type": "keyword",
                    "ignore_above": 128
                  },
                  "monotonic": {
                    "type": "boolean"
                  },
                  "startTime": {
                    "type": "date"
                  },
                  "@timestamp": {
                    "type": "date"
                  },
                  "observedTimestamp": {
                    "type": "date_nanos"
                  },
                  "value@int": {
                    "type": "integer",
                    "time_series_metric": "counter"
                  },
                  "value@double": {
                    "type": "double",
                    "time_series_metric": "gauge"
                  },
                  "buckets": {
                    "type" : "nested",
                    "properties": {
                      "count": {
                        "type": "long"
                      },
                      "sum": {
                        "type": "double"
                      },
                      "max": {
                        "type": "float"
                      },
                      "min": {
                        "type": "float"
                      }
                    }
                  },
                  "bucketCount": {
                    "type": "long"
                  },
                  "bucketCountsList": {
                    "type": "long"
                  },
                  "explicitBoundsList": {
                    "type": "float"
                  },
                  "explicitBoundsCount": {
                    "type": "float"
                  },
                  "quantiles": {
                    "properties": {
                      "quantile": {
                        "type": "double"
                      },
                      "value": {
                        "type": "double"
                      }
                    }
                  },
                  "quantileValuesCount": {
                    "type": "long"
                  },
                  "positiveBuckets": {
                    "type" : "nested",
                    "properties": {
                      "count": {
                        "type": "long"
                      },
                      "max": {
                        "type": "float"
                      },
                      "min": {
                        "type": "float"
                      }
                    }
                  },
                  "negativeBuckets": {
                    "type" : "nested",
                    "properties": {
                      "count": {
                        "type": "long"
                      },
                      "max": {
                        "type": "float"
                      },
                      "min": {
                        "type": "float"
                      }
                    }
                  },
                  "negativeOffset": {
                    "type": "integer"
                  },
                  "positiveOffset": {
                    "type": "integer"
                  },
                  "zeroCount": {
                    "type": "long"
                  },
                  "scale": {
                    "type": "long"
                  },
                  "max": {
                    "type": "float"
                  },
                  "min": {
                    "type": "float"
                  },
                  "sum": {
                    "type": "float"
                  },
                  "count": {
                    "type": "long"
                  },
                  "exemplar": {
                    "properties": {
                      "time": {
                        "type": "date"
                      },
                      "traceId": {
                        "ignore_above": 256,
                        "type": "keyword"
                      },
                      "serviceName": {
                        "ignore_above": 256,
                        "type": "keyword"
                      },
                      "spanId": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "instrumentationScope": {
                    "properties": {
                      "name": {
                        "type": "keyword",
                        "ignore_above": 256
                      },
                      "version": {
                        "type": "keyword",
                        "ignore_above": 256
                      },
                      "droppedAttributesCount": {
                        "type": "integer"
                      },
                      "schemaUrl": {
                        "type": "text",
                        "fields": {
                          "keyword": {
                            "type": "keyword",
                            "ignore_above": 256
                          }
                        }
                      }
                    }
                  },
                  "schemaUrl": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  }
                }
              },
              "settings": {
                "index": {
                  "mapping": {
                    "total_fields": {
                      "limit": 10000
                    }
                  },
                  "refresh_interval": "5s",
                  "mode": "time_series",
                  "routing_path": [
                    "serviceName",
                    "name"
                  ]
                }
              }
            },
            "composed_of": [],
            "version": 1,
            "_meta": {
              "description": "Observability Metrics Mapping Template",
              "catalog": "observability",
              "type": "metrics",
              "correlations" : [
                {
                  "field": "spanId",
                  "foreign-schema" : "traces",
                  "foreign-field" : "spanId"
                },
                {
                  "field": "traceId",
                  "foreign-schema" : "traces",
                  "foreign-field" : "traceId"
                }
              ]
            }
          }
        bulk_size: 4

entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
      port: 21890
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"

raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  processor:
    - otel_traces:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: trace-analytics-raw

service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  processor:
    - service_map:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: trace-analytics-service-map
